theme: jekyll-theme-cayman


description              : "4M Association"
baseurl                  : "/4m-association"
url                      : "ceryslewis.github.io"
repository               : "ceryslewis.github.io/bear-software-resources"

title_separator          : "-"
lang                     : "en-GB"
masthead_title           : "4M Association"

site_title               : "4M Association"
site_subtitle            : ""
site_title_url           : "/4m-association/"

uob_logo_path            : "https://bear-apps.bham.ac.uk/static/core/images/uob-logo.svg" # path of logo image to display in the masthead
uob_logo_alt             : "University of Birmingham logo"
uob_logo_url             : "https://www.birmingham.ac.uk/index.aspx"

search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google

reCaptcha:
  siteKey                :
  secret                 :

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Cerys Lewis"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : # "bio info"
  location         : "Somewhere"
  email            :
#  links:
#    - label: "Email"
#      icon: "fas fa-fw fa-envelope-square"
#      # url: mailto:your.name@email.com
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      # url: "https://your-website.com"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      # url: "https://twitter.com/"
#    - label: "Facebook"
#      icon: "fab fa-fw fa-facebook-square"
#      # url: "https://facebook.com/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      # url: "https://github.com/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      # url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: